### ISSUE TITLE
Chapter filtering by scanlation group

### ISSUE THREAD

**Issue by beer-psi** [Aidoku/Aidoku#100]
Add an option to chapter filters for hiding chapters from specific scanlators.

**Comment by kifujin** [comment]
How about setting priority for different groups? That way if a chapter only has one supplier you still see it, but otherwise still get the effect of filtering. Not sure what happens if you have one group posting split chapters and another a combined version.

**Comment by slushieeru** [comment]
What I think would be better would be a preference numbering set by the user, like eg i prefer:
1. official
2. favorite scanlation group
3.+ any other scanlation group that could fill in missing chapters

Even better if "skip duplicate chapters" used the highest available preferred group when reading, and likewise actually skipped chapters when in reading mode..

**Comment by fmunim** [comment]
Need this so desperately, its such a chore to follow a specific group within a manga that has more than 1 scanlation group
