### ISSUE TITLE
Automatic Online backups

### ISSUE THREAD

**Issue by leifyv** [Aidoku/Aidoku#104]
Add a way to do automatic backups once every week or so and upload it to dropbox/google drive/iCloud if possible. 
I’d say make a new backup every 5 days or so (or make it customizable for people) if there is a change in data, such as
> when there are new sources added
> when a new manga is added to collection, or change in how many chapters you have read
> when you move manga between categories or add/delete categories. 

and then be able to look through the timestamps on each backup and load it in the app if that is possible (not 100% sure on how much of that is possible) 
I personally lost a backup due to it corrupting on my phone and I think having a online backup/backups would be good for a decent amount of people. In case something happens or they swap phones. And it is a good feature to add in early. 

(edit: I know that iCloud sync is a thing but having alternate ways of backing up is good due to people maybe not having enough space in iCloud, or some other reason that could vary from person to person. personally, I don't have enough iCloud space for much else so that's why I am asking for new ways of having backups.)

**Comment by Skittyblock** [comment]
Ideally this should be done through #88, with some sort of ability to save the backup to a custom location.
