### ISSUE TITLE
Aidoku crashes when trying to read downloaded Chapter

### ISSUE THREAD

**Issue by DaLeberkasPepi** [Aidoku/Aidoku#106]
In the current Version 0.5 Build 2, when you try reading downloaded chapters i crashes after a few seconds and only ever displays a blank black page with a loading circle. And for me at least it only seems to occur when i enable the experimental invinite vertical scroll feature.

I havent tried any other version for the moment.

**Comment by 3lack3ox** [comment]
I am also having the same issues, downloaded chapters don’t load and then app crashes after

**Comment by frailbongat** [comment]
+1

**Comment by RiseAndCry** [comment]
On iphone 13 pro max i've tried viewing the downloaded chapter and it lags terribly, sometimes crashes as well. What's aeird is that the UI also becomes barely responsive. So this seems to be a performance issue. If i delete the chapter and view it via wifi instead - everything works fine.
Changing settings do not impact the experience.
