### ISSUE TITLE
Library and manga updated chapters

### ISSUE THREAD

**Issue by suirobert** [Aidoku/Aidoku#117]
Library refresh doesn’t work at all, I have to enter a manga and refresh for it to be updated with a new chapter because new chapters don’t show up

**Comment by Skittyblock** [comment]
Probably consult the information about DDOS mitigations. Library refresh skips a lot of titles. There was an issue that might've actually caused something similar, but it was fixed in 8711cc151fe3a0b9659b236243fb05d5c1940874 (not on testflight yet).
