### ISSUE TITLE
Suggestion - Option to remove navigation bar labels

### ISSUE THREAD

**Issue by OBJ100** [Aidoku/Aidoku#123]
Option to be able to remove navigation bar labels
![51B3651E-7352-4C17-A079-6B8852A5FE9A](https://user-images.githubusercontent.com/118631741/202867711-60272ffb-fa9f-4b5e-8770-53b0f9781ad6.jpeg)

**Comment by Skittyblock** [comment]
Probably won't add this. There will be a theme system in the future, but how capable it'll be remains to be seen.
