### ISSUE TITLE
Duplicate tracking not working

### ISSUE THREAD

**Issue by Armastardo** [Aidoku/Aidoku#133]
If you're already tracking a manga with anilist and try to track it with another title, you get no error message and no information about it; it just doesn't track.

This is troublesome because if a title is removed from a source and you didn't remove the tracking, you will no longer be able to track it again with a different one (this is what I'm experiencing right now).

Instead, a confirmation dialog such as "This manga is already being tracked, what would you like to do" and  options being "Cancel", "Overwrite" and "Go to tracked title" would be best. If you'd preffer to allow duplicate tracking, that'd be good too.

**Comment by Skittyblock** [comment]
Thanks for letting me know about this, I didn't realize. It should allow duplicate tracking.
