### ISSUE TITLE
Default reader doesn't work until added to library

### ISSUE THREAD

**Issue by beerpiss** [Aidoku/Aidoku#135]
The "Default" reading mode is supposed to be determined by the source, however it does not work (defaults to rtl) unless the entry is added to library.

### Version
0.6 (8)

### How to reproduce
1. Open a manhwa/manhua chapter from sources that automatically set webtoon viewer (AsuraScans, etc.)
2. See that Default viewer is right-to-left
3. Add the manhwa/manhua to library and open a chapter again
4. See that it is now properly using the webtoon reader

**Comment by Skittyblock** [comment]
this was fixed by 4b415e4167cb59a39e3a0aec2e2b84df4b48c852
