### ISSUE TITLE
Feature to save manga panels!

### ISSUE THREAD

**Issue by mukeshmx** [Aidoku/Aidoku#142]
We could have a dedicated button in library section of the app for looking into panels we saved.

**Comment by Skittyblock** [comment]
I think this isn't really within the scope of the app. Your best bet is just saving the images to your photo library and then making an album you can put them.

**Comment by AzSiAz** [comment]
You could add a specific album where images are saved like WhatsApp is doing for exemple inside the photo app

**Comment by Skittyblock** [comment]
yeah I was thinking about that. I could maybe add an option to save all images to an album in the photos app
