### ISSUE TITLE
App crash while refresh manga during download

### ISSUE THREAD

**Issue by mossicrue** [Aidoku/Aidoku#145]
Step to reproduce the bug:
- go to any manga you add
- select one or more chapter
- start download
- pull down to refresh during the download
- the app crashes.

NOTE: If you change the language of the source before start download, the pull to refresh action will instead change the chapter listed and the app don’t crash

**Comment by Skittyblock** [comment]
**Thank you** for giving reproducible steps. I'll have this fixed in the next update.
