### ISSUE TITLE
OptionBar in chapterviewer

### ISSUE THREAD

**Issue by codewithac** [Aidoku/Aidoku#147]
Is it possible to move the optionbar/navigationbar from top to bottom in the chapter reader/viewer. Hope the image helps to clarify
![D6E9EA44-0459-4E34-B989-8F6C50AE7D51](https://user-images.githubusercontent.com/122235859/211221172-1b449cc8-6b48-43d2-b3c0-56faa7503cbb.jpeg)

**Comment by Skittyblock** [comment]
I don't think this is really within scope for the app since it's a minor UI change for personal opinion and breaks apple design guidelines.
