### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by xoxyuuji** [Aidoku/Aidoku#149]
Hi, nice to meet you. Look, I don't speak English, and I might be wrong trying to explain myself. About the sources topic, I'd like to know if in the future, an option to add sources like MangaPLUS would come up, would be added to Aidoku. I'm very new. I used to read mangas on Tachiyomi, but I don't use an android phone as my personal phone. And I read on MangaPLUS because the most of time the translation is very, very good. Some scans doesn't have a really good one, mostly. I want to help to improve Aidoku because I really believe that is the best manga app I have tested on iPhone, I really do. I helped with the tachiyomi fork translation. I speak Spanish, btw. Sorry, and thanks if you read all of this.

**Comment by JaviSede** [comment]
It will be very nice for the Spanish community, InManga is too a fabulous option, Ninemanga, leercapitulo.com and more. Thx for reading

**Comment by Skittyblock** [comment]
You can request sources elsewhere, Aidoku doesn't have control over any external sources.
