### ISSUE TITLE
Locked Categories and Rename/Delete

### ISSUE THREAD

**Issue by JBLOGNON** [Aidoku/Aidoku#150]
Hi, I think I have discover somes issues related to Categories Renaming and "Locked Categories".

My app version is: 0.6.1 (2)

First, when you rename a locked category, it is no longer locked. On the other hand its old name seems to be still in memory (in the list of locked categories) but not displayed, because if you give back its old name to the previously modified category it becomes locked again. 

Steps to reproduce :
- Go to Settings
- Create a new Category "test"
- Lock this Category
- Check that it is locked in the Library
- Return to settings and rename the Category to something else
- Check in the Library: the Category wont be locked anymore (but the "All" category will still be locked !)
- Return to settings and rename the Category back to "test"
- Check in teh library the Category will be locked back

Second, when you have for exemple 1 locked category, if you delete this category the "All" category will remain locked even if in theory we don't have any more categories to lock because we have deleted it.

An finaly, a minor issue, but some times (when we reopen the app) the lock icon is not displayed on categories list.

<img src="https://user-images.githubusercontent.com/43005236/212485797-1924cf47-6f9b-476b-9cc5-12fca1bb85b3.png" width="200" /> | <img src="https://user-images.githubusercontent.com/43005236/212485798-52c761ec-11e0-412e-9b5f-678fcd58b354.png" width="200" /> | <img src="https://user-images.githubusercontent.com/43005236/212486240-687b2d44-1874-4526-8c69-416251653b83.png" width="200" />

Hope this will help you ;)

**Comment by Skittyblock** [comment]
Sorry I didn't see this until now! Your issues should be fixed now (or, at least, in the next update). Thanks for giving detailed reproduction steps.

> if you delete this category the "All" category will remain locked

Yes, this is actually intended. You still have the "lock library" setting enabled, so All will remain locked until that is turned off.
