### ISSUE TITLE
sources in pt-br pls

### ISSUE THREAD

**Issue by LANK7** [Aidoku/Aidoku#153]
I'm Brazilian and I'm sorry if my English is bad... but I would like to humbly ask that you make souces in PT-BR preferably from these sites.
reaperscans.net
https://mangalivre.net
https://www.goldenmangas.top
https://hentaiteca.net
https://www.manhwas.net
https://randomscans.com
https://gekkou.com.br

**Comment by Skittyblock** [comment]
Request where you requested before. Aidoku doesn't have any control over external sources made for it.
