### ISSUE TITLE
Add a Search bar to the Migration menu

### ISSUE THREAD

**Issue by pandeynmn** [Aidoku/Aidoku#162]
### Feature

Upon clicking a Migrate-to cell in the Migration menu, the app presents list of available sources that have been pre-selected. There should also be an option to search a specific source in that list with a user defined search string. The Manga cells in the list should also open a Manga view for the user. 

### Why
Some sources like _Asurascans_, may encounter server-side limitations that prevent them from conducting full title searches.(e.g. the title having an apostrophe). This can result in false negatives, indicating that a particular title is not available on the source, as demonstrated in this [example](https://i.imgur.com/qx7Jrtn.png) existing [here](https://www.asurascans.com/manga/ill-be-taking-a-break-for-personal-reasons/). To mitigate this issue, it is recommended that manual search options be considered as a work around in finding the title. 

Some sources, such as _Batoto_, may have multiple versions of the same title in various languages or with varying chapter counts. Being able to open the Manga view to confirm these details would help in selecting accurate titles for migration.

**Comment by KaBankz** [comment]
> Some sources like Asurascans, may encounter server-side limitations that prevent them from conducting full title searches.(e.g. the title having an apostrophe).

MangaStream sources such as Asura should have working search after [this](https://github.com/Skittyblock/aidoku-community-sources/pull/133) pr is merged, specifically by [this](https://github.com/Skittyblock/aidoku-community-sources/pull/133/commits/f13c36d836ac82dcf0bf131a4eda6b1e0941f830) commit. This does not cover all cases, but should fix most missing results in migration for MangaStream sources only.

**Comment by pandeynmn** [comment]
> > Some sources like Asurascans, may encounter server-side limitations that prevent them from conducting full title searches.(e.g. the title having an apostrophe).
> 
> MangaStream sources such as Asura should have working search after [this](https://github.com/Skittyblock/aidoku-community-sources/pull/133) pr is merged, specifically by [this](https://github.com/Skittyblock/aidoku-community-sources/pull/133/commits/f13c36d836ac82dcf0bf131a4eda6b1e0941f830) commit. This does not cover all cases, but should fix most missing results in migration for MangaStream sources only.

Asurascans was just an example, Reaperscans also has shit search so it has trouble locating full titles. Some sources use alternate names for titles etc.

**Comment by Skittyblock** [comment]
skipping the manga view because I don't think it'd have that much of a use case, but if you really want it you can make a new issue
