### ISSUE TITLE
the last chapter read is not counted if the manga has multiple translations

### ISSUE THREAD

**Issue by execOQ** [Aidoku/Aidoku#163]
if the manga has multiple translations, then the last chapter read will count only if all translations are read.  In the video, I have already read 34 chapters, but the "continue reading" button is still on the second chapter.

https://imgur.com/a/L2li1NZ

P.S: it would be great to add the ability to filter translations

**Comment by Skittyblock** [comment]
That's intended. The read button uses whatever the lowest chapter not read is, and since you haven't read or marked read the chapters from other scanlation groups, it attempts to read from there.

I think your issue will be fixed with #100 though. For now, just mark all chapters as read.
