### ISSUE TITLE
Marked all previous chapters as read, still shows ## unread on poster

### ISSUE THREAD

**Issue by Daptonic** [Aidoku/Aidoku#164]
Hey there ... coming back to Aidoku after a while and when marking some chapters I read elsewhere "as read", I see that change in the titles info page, but on the library page it still shows ## of unread badge.

It's not always the max number of chapters in the title either, it's a random number. For example, in one of titles the total chapters are 72 and I marked them all as read and when I look at the Info page, they're all marked as read, but the library view still shows a random 50 unread chapters badge. This makes it difficult to know which titles I am reading have new chapters at a glance.

Ver 0.6.1 build 3

**Comment by Skittyblock** [comment]
Can you try migrating chapter history in settings at the bottom?

**Comment by Daptonic** [comment]
Aha! that appeared to do the trick. Thank you :)
