### ISSUE TITLE
Unread manga pin does not update

### ISSUE THREAD

**Issue by robkooper** [Aidoku/Aidoku#165]
I have unread manga pinned and I have all unread manga at the top. When I finish a manga it stays pinned to the top and does not go the bottom half. This was working correctly before yesterdays update.

**Comment by Skittyblock** [comment]
Fixed with 930633a31c68f3c5dfaafb36d338168dc301876b

**Comment by robkooper** [comment]
Not sure this got fixed

![image](https://user-images.githubusercontent.com/1580696/217716990-c3c87e2b-8f79-4c7f-99e7-dd01be395b1f.jpeg)

**Comment by robkooper** [comment]
Checked on my phone and it works. You can leave it closed while I try to reproduce on my tablet and phone

**Comment by Skittyblock** [comment]
Actually yeah, someone told me on the discord that it wasn't fully working still and it turns out it doesn't work with certain sort options (e.g. by title).
