### ISSUE TITLE
MAL Tracker not updating

### ISSUE THREAD

**Issue by Goharn** [Aidoku/Aidoku#178]
There’s an issue with MAL Tracker, the chapter numbers get updated but the status does not. 

Like when you select completed or dropped, it does not get updated on the website but it will show that it’s changed in the application.

**Comment by Skittyblock** [comment]
If you close the tracker view and reopen it again does it still say completed or dropped?

**Comment by Goharn** [comment]
Doesn’t change, it stays in the orignally set status.

**Comment by Skittyblock** [comment]
I think this might be due to the API token expiring and not being able to be refreshed. Logging out and back in should fix it (but it removes all your tracking and you have to re-add stuff manually). I'll see if there's anything I can do about it.

**Comment by Goharn** [comment]
It still says the same even after I log out and set tracking again.
