### ISSUE TITLE
Unable to refresh Chapter list on IpadOS

### ISSUE THREAD

**Issue by melfranciz** [Aidoku/Aidoku#188]
Just noticed an issue where the chapter list does not refresh for any manga on the ipad (dragging down the page forces a refresh of the chapter list). Seems to work fine on the iphone. Tried the following to fix:

- Reinstalling the app
- Clearing cache and resetting
- Trying different sources

**Comment by Skittyblock** [comment]
You're saying that you can't trigger the refresh or the refresh doesn't do anything? You need to pull down on the left hand side of the screen.

**Comment by Skittyblock** [comment]
Yeah, if that's something you'd want feel free to open an issue for it and I can consider it
