### ISSUE TITLE
low manga panel quality when i zoom in 

### ISSUE THREAD

**Issue by 121254** [Aidoku/Aidoku#190]
[whenever]() i try zooming in the panels the picture gets low quality, i tried with other sources and same thing happens, i checked with other manga reader apps and this issue is not there

**Comment by 121254** [comment]
Uploading IMG_0967.MOV…

**Comment by 121254** [comment]
![D0E10EA8-9D4C-4581-9479-7DD203466F8D](https://user-images.githubusercontent.com/126649066/222063105-94ef2a32-1c2c-4897-8561-d74eec13e6f4.jpeg)

**Comment by Skittyblock** [comment]
This is the intended function of the downsample images option. It reduces stuttering caused by rendering high quality images. If you'd rather see images in their original quality, you can turn this off, but the consequence might be slower image loading and lagging.

**Comment by 121254** [comment]
> This is the intended function of the downsample images option. It reduces stuttering caused by rendering high quality images. If you'd rather see images in their original quality, you can turn this off, but the consequence might be slower image loading and lagging.

how do i turn this off?

**Comment by Skittyblock** [comment]
it's "Downsample Images" in reading settings
