### ISSUE TITLE
App crashes when page is shared (iPad)

### ISSUE THREAD

**Issue by ash10r** [Aidoku/Aidoku#197]
![0909EAA6-DE0C-4416-ADF8-EBD82E4584F0](https://user-images.githubusercontent.com/78199278/226988173-59ffe5eb-e42f-443e-ab67-529c477dd85a.png)

Using iPad 6th generation (iPadOS 16.3.1) app version 0.6.1

if I click the share button as in the screenshot, the app will crash.

 This is a 100% occurrence.

**Comment by ItsLame** [comment]
Fix: #230
