### ISSUE TITLE
Suggestion: Pin Sources

### ISSUE THREAD

**Issue by SioFreed** [Aidoku/Aidoku#201]
I would like an option to pin sources to the top of the list please. While I try to use the original TL sites, I usually default to only 3 for reading/discovering, so being able to find them easily would be really nice.

Thank you for all the hard work creating this app.

**Comment by Skittyblock** [comment]
the reason I haven't really prioritized this is because it's not ideal to have more than a few sources in the first place, and it isn't really great to incentivize it, but this is a feature I planned anyways
