### ISSUE TITLE
Multiple Scaners for the same language.

### ISSUE THREAD

**Issue by Megaatroon** [Aidoku/Aidoku#217]
It's really difficult to download mangas with a lot of chapters when there are multiple scanners and I have to download every chapter alone to avoid double chapters and can't use multi select because this will consume my phone storage.

![image](https://user-images.githubusercontent.com/86772939/231440217-7ff0b4c8-de72-4be8-a481-72f36a0a2a6c.jpeg)

**Comment by Skittyblock** [comment]
You can use multi-select. We will add more download options in the future.
