### ISSUE TITLE
Add Traker's Cover

### ISSUE THREAD

**Issue by Megaatroon** [Aidoku/Aidoku#218]
Option to replace the source cover with that of the tracker 
because it's usually of high quality and more familiar.

![image](https://user-images.githubusercontent.com/86772939/231442389-4218b0d7-b79c-43b2-8cbe-3ae042a66c48.jpeg)
![image](https://user-images.githubusercontent.com/86772939/231442404-33b41763-941b-46a2-b362-8790228cbb9e.jpeg)

**Comment by Skittyblock** [comment]
#65 will cover this
