### ISSUE TITLE
Unread chapters badge issue

### ISSUE THREAD

**Issue by AshenPaladin** [Aidoku/Aidoku#219]
### Description

Several manga series have an issue with their unread chapter badges - unread chapter badges appear despite all of the chapters being read and no new/unread chapters existing. Furthermore, trying to select all the chapters and to mark them as read again for such series results in the app crashing.

 ### Steps to Reproduce

 1. Open the manga app.

  2. Check for manga updates in the library.
 
  3. Observe that some manga series have unread chapter badges despite there not being any unread chapters.

 4. Open the series in question

  5. Select all chapters and mark them as read
    
 

 ### Expected Behavior

Unread chapter badges should only appear if there are unread chapters.
 ### Actual Behavior
 
Unread chapter badges appear randomly for some series despite there not being any unread chapters
 ### Additional Information
 
* The issue occurs daily.
* The app is used on a regular basis.
 * The issue affects the user experience negatively.
* The issue becomes progressively worse, affecting more and more series
 
 ### Video of the issue

https://user-images.githubusercontent.com/64322403/232053886-d380f1f1-67b6-41cf-869f-5ac01b8a863d.mp4

**Comment by Skittyblock** [comment]
I'm unsure about a permanent fix for this, but you can use Migrate Chapter History in settings to fix it temporarily. I believe you can fix it for a series permanently by marking all chapters unread and then read. I'm not sure the exact cause or solution yet though...

**Comment by AshenPaladin** [comment]
Neither of those work for me unfortunately. Migrating chapter history does nothing that I can notice, and marking all chapters read or unread also doesn't seem to fix it. The app crashes twice, first when I mark them all unread, and then when I'm marking them all read, and that same one unread chapter badge remains.

Some further info that might help:

- I am using iCloud Sync so the issue appears on both my iPhone and iPad
- I already had this issue once before, so I proceeded to uninstall the app and delete all of its data in iCloud. After reinstalling, I had almost a week of no issues, no wrong unread chapter badges and no problems with marking all the chapters of a series read or unread.
-For now the issue seems to only affect those three series. Back the first time when I had this issue, it progressively affected more and more series, but for now it seems to not be spreading.

**Comment by Skittyblock** [comment]
ohh so it's probably an icloud sync issue, I see

**Comment by Skittyblock** [comment]
Duplicate chapters should be fixed by 1149897740df61c463ba54c45e1c917a51df33b3, so hopefully iCloud sync doesn't cause any more issues like this now.

**Comment by AshenPaladin** [comment]
I’ve unfortunately encountered this issue again on 0.6.3, with multiple different series. It does seem to be an iCloud sync related issue as the wrong unread chapter badges appeared on the same day I opened the app multiple times on both my iPhone and my iPad.

Removing the series from library and adding it right back does seem to at least temporarily fix the issue, but since it seems to be the same thing I can’t provide much more info.

Is there anything else I should try, like deleting my iCloud data for the app and starting fresh?

**Comment by Skittyblock** [comment]
It should be corrected if you pull to refresh inside a manga page. It could be the same issue resurfacing without having been fixed, or it could be a result of the stored cloudkit data still containing duplicates and not correcting itself. Feel free to make a new issue, specifically about icloud object duplication, if it doesn't fix itself.
