### ISSUE TITLE
Selecting multiple chapters

### ISSUE THREAD

**Issue by CritLoren** [Aidoku/Aidoku#225]
Hello,

Could we get a way to select multiple chapters at once? A clean way to implement it would be having to go into select mode, then selecting a chapter to select a beginning and hold pressing another to select the end which then selects all chapters in-between as well.

Thank you

**Comment by Skittyblock** [comment]
manga page -> top right ellipsis menu -> select chapters -> drag along the dots if you want to select multiple quickly

**Comment by CritLoren** [comment]
oh wow that's cool didn't know you could do that
