### ISSUE TITLE
Dual pages get scaled incorrectly on ipad

### ISSUE THREAD

**Issue by CritLoren** [Aidoku/Aidoku#227]
Dual page layouts on iPad get scaled incorrectly, the left page looks like it's set to fill height while the right page fills the remaining space. The page scaling is fine when rotating from a single page to two pages, but subsequent layouts when scrolling to the next set will exhibit this issue.

If the pages out together are narrower than the iPad width (in landscape mode) the issue does not show up. The scaling only gets broken when the pages added up are wider and need to be scaled based on width.

**Comment by Skittyblock** [comment]
#184 duplicate
