### ISSUE TITLE
Share action doesn't do anything on iPad

### ISSUE THREAD

**Issue by ItsLame** [Aidoku/Aidoku#231]
Whilst fixing #197. I noticed that the share action on iPad doesn't do anything. This is my first time using Swift, so I'm not sure how to approach this.

https://user-images.githubusercontent.com/37344470/233849918-7ce51889-a335-4e6a-b560-1e2b4c39c692.mp4

**Comment by Skittyblock** [comment]
Same bug as #197, but inconsistent behavior

**Comment by ItsLame** [comment]
Fix: #230
