### ISSUE TITLE
Read History is wiped

### ISSUE THREAD

**Issue by Megaatroon** [Aidoku/Aidoku#237]
At the beginning i though it may be because of the jailbreak and the reboot but it happened again and this time i didn't reboot my phone.

Note : i used filza to install the ipa.

**Comment by Skittyblock** [comment]
Was every chapter you had read marked unread?
Was the history tab empty?
Do you have iCloud sync enabled and do you use multiple devices with Aidoku?

**Comment by Megaatroon** [comment]
Yes all my Mangas are marked as unread and I use icloud sync and i use Aidoku only on one device this problem happen when i reboot my device and rejailbreak too but this time it happened without any reboot or rejailbreaking.
 
All are marked as unread but syncing with the tracker is still there not wiped as the read History.![image](https://github.com/Aidoku/Aidoku/assets/86772939/80fb42f8-df52-4bab-bbd4-46d9afb1bc47)

**Comment by Skittyblock** [comment]
it happens every time you reboot and re-jailbreak? How do you have Aidoku installed? Through TestFlight or the ipa?

**Comment by Megaatroon** [comment]
Through Filza.

**Comment by Skittyblock** [comment]
Try disabling iCloud sync. I'm not sure if it'd work anyways through an ipa installed with app sync. I feel like this is some issue related to that.

**Comment by Megaatroon** [comment]
Disabling iCloud seems to work even with the reboot and rejailbreak.

**Comment by Skittyblock** [comment]
Gonna assume this is just an iCloud issue which is related to #111. If you're installing the ipa without a dev account I doubt iCloud will ever work, so that might be what's causing this particular issue.
