### ISSUE TITLE
Images scaling incorrectly in landscape.

### ISSUE THREAD

**Issue by anero-0** [Aidoku/Aidoku#238]
Everything after the first page viewed scales incorrectly in landscape (image 1 is page if it’s the first one opened, image 2 is the same page if I flip to it from a different one)
![IMG_0017](https://github.com/Aidoku/Aidoku/assets/126972510/d1cd05f4-c317-4d54-b806-6e598ec109e6)
![IMG_0016](https://github.com/Aidoku/Aidoku/assets/126972510/75af2e85-c9f8-4098-b5e4-9c94b58f3217)
)

**Comment by Skittyblock** [comment]
duplicate #184
