### ISSUE TITLE
Automatically close after importing sources when sideloaded with tools outside of altstore

### ISSUE THREAD

**Issue by Roroca-1** [Aidoku/Aidoku#239]
altstore itself is very buggy so I've tried many other sideloading apps that uses .p12 certificates to sign and sideload apps on to my device, but with the case of Aidoku, whenever i finish improting all the sources and restart the app after, the app opens and becomes this translucent interface before closing itself automatically shortly after.

**Comment by Roroca-1** [comment]
![IMG_0491](https://github.com/Aidoku/Aidoku/assets/81666000/7eca72e8-f2ea-41f1-bdb6-3f7e4f048add)
the translucent interface after opening aidoku

**Comment by Roroca-1** [comment]
Sometimes when I finish reinstalling Aidoku this problem does not immediately occur, in one case it occured right after i turned on the iCloud Sync option in settings.

**Comment by Skittyblock** [comment]
This is the app crashing, which will happen either if the certificate expires or if iCloud sync is enabled. iCloud sync is supposed to be disabled when you sideload, as it only functions in TestFlight.
