### ISSUE TITLE
MAL tracker search results media type always “Manga”

### ISSUE THREAD

**Issue by Haulien** [Aidoku/Aidoku#249]
When choosing an item to track using MAL, every item reads as “Type: Manga” even though there are light novels and one-shots in the list. 

Using the example below, a search on MAL reveal what’s what and comparing the manga name on-site and what’s in the app is pretty straightforward, however there’s plenty of manga that share identical naming with their LN counterpart and picking which is which can be confusing. 

This also appears to be MAL exclusive, AniList shows the correct medium in the search results. 

Screenshot from the list of manga to track from with indicators of what’s what. 

![IMG_0100](https://github.com/Aidoku/Aidoku/assets/640569/e4824bc4-0971-4f01-b1ea-e929ab226bf5)

Screenshot of MAL search results with the correct medium in the right most column. 

![IMG_0101](https://github.com/Aidoku/Aidoku/assets/640569/c6383a57-6ce3-4657-b3bf-649ca4a75400)

**Comment by Skittyblock** [comment]
Thanks, I'll take a look.
