### ISSUE TITLE
Duplicate library manga and chapters

### ISSUE THREAD

**Issue by magnetardev** [Aidoku/Aidoku#25]
This is for all sources I've tried (so assuming an actual aidoku bug).

Sometimes when you go into a manga view the chapters will just list twice (and the chapter count will be double what it actually is).

This only happens in the library. Allegedly an iCloud Sync thing.

**Comment by HeyItsMicro** [comment]
Bees are actually allergic to pollen, they develop hives.

**Comment by AzSiAz** [comment]
Skitty, I don't know if you are aware but `NSPersistentCloudkitContainer` doesn't handle deduplication...

**Comment by Skittyblock** [comment]
Yes, I am aware. I thought the merge policy would though, but I'm not very well-versed in CloudKit details. I'll have to look into it more.

**Comment by AzSiAz** [comment]
Not sure how duplicate happened here but it would only work if core data objectID is the same, if you have the same manga in library from another device it would result on a different objectID thus a duplicate in both device since core data unique key does not work with CloudKit enabled

**Comment by Skittyblock** [comment]
This should be resolved now, but when #37 is resolved it should be more robust. I added de-duplicating methods for library manga and reading history, and chapters can be de-duplicated by refreshing in the manga page.
