### ISSUE TITLE
Library Storage Manga bug

### ISSUE THREAD

**Issue by AlanNois** [Aidoku/Aidoku#258]
If the domain of the web changes the whole chapter tracked is missing or doesn't update except refresh the manga but after refresh it also missing tracked chapter
SUGGESTION:
Storage domain of website like {Domain name}/path-to-manga or create an array like arr = [0,0,0,0,0,0,0,0] for each chapter if the user clicked chapter to read arr will be updated like click chapter 2 arr = [0,0,1,0,0,0,0,0]

**Comment by Skittyblock** [comment]
This is entirely source dependent. Sources define their own ids, and 99% of them shouldn't use the base url in the id anyways since it's bad practice.
