### ISSUE TITLE
Last update sorting not working if add "old" manga

### ISSUE THREAD

**Issue by mossicrue** [Aidoku/Aidoku#270]
**Description of the problem:**
Sorting Manga Library by "Last Update", after adding a Manga with the latest chapter old, like Hunter x Hunter or finished manga, not working properly, showing first the last added Manga to Library

**Expected Results:**
Manga sorted by latest chapter date even if freshly added

**How to reproduce it:**
1. Set Library sorting options to "Title"
2. Add a manga that isn't recently updated, like Hunter x Hunter (rip) or a finished one
3. Set Library sorting options to "Latest Update"
4. Added Manga is on top

**Comment by Skittyblock** [comment]
Latest update sorts by whenever the manga was last updated by Aidoku, not by the latest chapter upload date. When you add the manga to your library, that's counted as an update, and if it gets refreshed with new chapters that is also counted as an update. I agree that this is kind of confusing, and there should be a sort by latest chapter option, but the way it works right now is intended.
