### ISSUE TITLE
Selectable Title in Manga View

### ISSUE THREAD

**Issue by aphronyx** [Aidoku/Aidoku#273]
Sometimes users might want to find manga reviews. It would be more convenient to make the title in manga view selectable, which could trigger edit menu and let users tap ‘Look Up’ button, or to tap title to copy to clipboard.

## Feature Request

- Selectable title
- Tap title to copy to clipboard

**Comment by aphronyx** [comment]
@Skittyblock #344

**Comment by Skittyblock** [comment]
the plan is to have it search by author on tap with the new source api, but it's able to be copied now

**Comment by aphronyx** [comment]
> the plan is to have it search by author on tap with the new source api, but it's able to be copied now

@Skittyblock 
Did you comment on the wrong issue? 👀

**Comment by Skittyblock** [comment]
no i'm just braindead and somehow merged the title and the author text in my mind bc im working on that rn lol, but yeah this issue was covered by #344
