### ISSUE TITLE
Pages not loading in horizontal orientation.

### ISSUE THREAD

**Issue by Jamerrone** [Aidoku/Aidoku#275]
Since the last update, some pages do not load or show in horizontal orientation. Vertical seems fine, but once I turn the phone it stops working. Especially the early pages seem bugged. https://github.com/Aidoku/Aidoku/assets/16142485/c475e1ab-6128-455b-8622-a02be4cee5ea

**Comment by Skittyblock** [comment]
pretty sure this is what I fixed with 0069c4dbf58fb021d71296a888e09e34c7ce24f2, since the chapter there is downloaded

**Comment by Jamerrone** [comment]
> pretty sure this is what I fixed with 0069c4dbf58fb021d71296a888e09e34c7ce24f2, since the chapter there is downloaded

It seems to be working again when scrolling down, but it breaks when scrolling up.

**Comment by Skittyblock** [comment]
Sounds like you didn't update

**Comment by Jamerrone** [comment]
> Sounds like you didn't update

Yeah my bad, it’s fixed. Thanks a lot.
