### ISSUE TITLE
A few ideas for improving the macOS app

### ISSUE THREAD

**Issue by TheFermi0n** [Aidoku/Aidoku#280]
I have a few suggestion that, I believe, will improve Aidoku in macOS.

### Reader view

- [ ] Use of `up` `down` `left` `right` keys to change page
- [ ] `Esc` key to close the reader view
- [ ] Some key combination to open the Chapter list (e.g., `cmd+B`) and Reader settings (e.g., `cmd+\`)
- [ ] Fix the pillar box issue as mentioned in #204 

### Detail view

- [ ] Fix the issue of volume changer in tracker #279 

### Library

- [ ] A dedicated button or key combination (e.g., `cmd+R`) to refresh the library. Current pull to refresh is very hard with both Touch pad or external mouse. 

P.S. I will keep adding to this if I find anything more. I understand that there are limitations as it is not a dedicated macOS application.

**Comment by Skittyblock** [comment]
Thanks for the suggestions, but it's best if these are put as separate issues rather than a single one. I can track them better.

Also, keyboard controls could be put as a single issue. They used to be implemented but I removed them because the code wasn't the greatest and I never rewrote them.
