### ISSUE TITLE
Adding webnovel sources?

### ISSUE THREAD

**Issue by riasavi** [Aidoku/Aidoku#285]
I dunno if this is the right place to put it, but I was thinking it would be cool if we were able to read web novels on Aidoku as well as manhwa and manga.

**Comment by pandeynmn** [comment]
Aidoku most likely won't do Light Novel sources. Soshiki is an app that does Light novels too written my Jim. 
https://soshiki.moe/

**Comment by Skittyblock** [comment]
aidoku is only for images. if there's a web novel site that uses images for pages then it can be made into a source, otherwise it's out of scope.
