### ISSUE TITLE
Downloaded files not working offline

### ISSUE THREAD

**Issue by Hypasurge** [Aidoku/Aidoku#292]
I have many manga and manwha downloaded and none of them work offline even though I downloaded them. Some short ones work whereas pretty much all of the bigger ones don’t work at all

**Comment by Skittyblock** [comment]
which source(s)? how long ago did you download them?

**Comment by ahmedelshwadfy2017** [comment]
I think this happens when you are downloading chapters and internet connection is lost then chapters will appear as downloaded but actually they aren't.

**Comment by Megaatroon** [comment]
I think this happens when you are downloading chapters and internet connection is lost then chapters will appear as downloaded but actually they aren't.

**Comment by Skittyblock** [comment]
#243 is the same issue then
