### ISSUE TITLE
Sushi-scan Source Not Working Anymore 

### ISSUE THREAD

**Issue by FoxyDr3am** [Aidoku/Aidoku#295]
After reading someone comment on discord the sushiscan source wasn’t working for him/her I tried it myself and it was working perfectly but I tried to uninstall it and install it again and now mine doesn’t work anymore I don’t think it’s an CF problem cuz they fix it already I don’t if you can it but thanks for your time checking it.
Ps: After I installed the source again I was still able to download the manga I saved up but If I tried to reload the manga page all the chapters/volumes will be remove by itself.

**Comment by Skittyblock** [comment]
the aidoku app doesn't manage any sources itself, this is the wrong location for the issue
