### ISSUE TITLE
Sushi-scan source is broken

### ISSUE THREAD

**Issue by ryo-sama** [Aidoku/Aidoku#296]
Hi, sorry to bother you, it's been a while since the Cloudfare protection for the sushi-scan source has gone but the source still doesn't work on Aidoku. Every time I launch it no manga is displayed even when refreshing it. I've uninstalled the application and reinstalled it, and I've even uninstalled the sushi-scan source and reinstalled it, but it still doesn't work. Can you fix it please? It's the only French source I'm interested in. Thank you very much for your work.

**Comment by Skittyblock** [comment]
people really love sushi scan wow #295
