### ISSUE TITLE
Unable to launch app at all

### ISSUE THREAD

**Issue by CraftedFury** [Aidoku/Aidoku#301]
I've been migrating my manga one at a time and this is the second time this has happened. I've just favorited Solo Leveling from ReadM (not sure if this was the cause the first time), and now I cannot launch the app whatsoever. Restarting my phone does not fix the problem.

Removing the app and re-sideloading it makes it launch again but I lose my entire library; I thought it was sync'd to iCloud?

[Aidoku-2023-08-08-203954.txt](https://github.com/Aidoku/Aidoku/files/12298021/Aidoku-2023-08-08-203954.txt)

https://github.com/Aidoku/Aidoku/assets/6407029/a195c4ca-e33a-4d6c-ae5c-e3f56992a8a0

**Comment by Skittyblock** [comment]
looks like it expired or something, this is a sideloading issue. icloud sync does not work outside of the testflight

**Comment by CraftedFury** [comment]
I have a paid developer account, it can't expire.
