### ISSUE TITLE
Ascending unread sort should put read chapters at bottom

### ISSUE THREAD

**Issue by ChronoStriker1** [Aidoku/Aidoku#307]
When the unread sort is set to ascending manga with zero chapters unread will show at the top of the list. I’m not sure if this is a bug or intended as that would be true to the sort, but ideally, the list should start with one unread, followed by any other number of unread, with zero unread being at the bottom, or having a filter for zero unread so the current sort works as expected. On the discord I’m being told that this is a bug but it could honestly go either way. If you need any more information, please let me know. I also provided a screenshot of what I was talking about in discord, but I can link it here if necessary.

**Comment by ChronoStriker1** [comment]
Also as a note as Im not sure if this is a factor or not (it was an issue with tachiyomi at one time) I have a very large list of manga in the app so I do not know if that is a contributing factor.

**Comment by Skittyblock** [comment]
not a bug, just something I didn't consider when writing it, but this would be a better way of handling it, thanks.
