### ISSUE TITLE
[Feature request] Load whole chapter on first page load of that chapter

### ISSUE THREAD

**Issue by Samk19** [Aidoku/Aidoku#310]
I am using webtoon mode and for titles like Eleceed etc there is a lag when moving from one page to another (i tried different network 4g 5g high speed wifi) and all of them have the same lag.

I would like to request a settings  option in future aidoku builds to load the whole chapter on initial load specially for webtoons.

**Comment by Jamerrone** [comment]
It's actually bugged at the time. There is a setting to control the amount of pages to preload, but it does not work with the webtoon reader. Sadly, it's the best reader but also the most buggy one.
