### ISSUE TITLE
[Feature Request] aidoku auto sync local status from remote traker status

### ISSUE THREAD

**Issue by Barusu-rem** [Aidoku/Aidoku#316]
Option for aidoku auto sync local status from remote status.

For example say I read a manga on aidoku and locally it recorded I read chapter 50 but anilist says I read chapter 55
Currently aidoku I have to go into the sync tab then manually trigger a sync to update the local status

Using aidoku (ios) along with Saikou (android) and main way of syincing is anilist not icloud

**Comment by Skittyblock** [comment]
someone else already made #306
