### ISSUE TITLE
i can't toggle the icloud sync

### ISSUE THREAD

**Issue by Salamander6850** [Aidoku/Aidoku#324]
Iphone 12ios version 16.6

**Comment by Jamerrone** [comment]
TestFlight or AltStore? Only works with the TestFlight version.

**Comment by Skittyblock** [comment]
this is intended. icloud sync is disabled when sideloading since it only functions when installed through TestFlight.

**Comment by Jamerrone** [comment]
@Skittyblock should you not have waited for his answer? We don't know for sure how he installed it yet.

**Comment by Skittyblock** [comment]
it's not possible for the option to be disabled unless the bundle identifier for the app is different from `xyz.skitty.Aidoku`, which is impossible for the TestFlight version.
