### ISSUE TITLE
Unable to Get the Last Sibling of Elements

### ISSUE THREAD

**Issue by aphronyx** [Aidoku/Aidoku#325]
I’ve encountered this problem since my first source, and I couldn’t figure out why.
This might be the reason?
https://github.com/Aidoku/Aidoku/blob/fc78be8d086b598a31e6c6ee3bc79d34d52e3a85/Shared/Wasm/Imports/WasmHtml.swift#L34-L35

**Comment by Skittyblock** [comment]
......oops. thanks
