### ISSUE TITLE
Shinigami domain change

### ISSUE THREAD

**Issue by adaaamxs** [Aidoku/Aidoku#332]
hi dev, i think shinigami id sources need update(idk bcs changing domain or what) because the source showing this

*
![29FA4FDC-6ACD-49AB-B78A-368819E03613](https://github.com/Aidoku/Aidoku/assets/143752827/01bfef96-55ff-482e-a247-4b97d61baeaf)
![E71D9FA9-54E1-4F2C-9744-2042602FFFE9](https://github.com/Aidoku/Aidoku/assets/143752827/b4e57d1e-e57b-45ae-8aa9-832e493a5439)
changes: migrated from https://shinigami.id/ to https://shinigami.ae/

**Comment by Skittyblock** [comment]
oops wrong repo
