### ISSUE TITLE
Downloaded chapters disappear if you refresh the screen while offline.

### ISSUE THREAD

**Issue by Jamerrone** [Aidoku/Aidoku#336]
Ran into this yesterday, I didn't go offline, but my manga source did (which results in the same). This is a normal occurrence as I host my own manga and the server is only online when I turn my pc on. Anyway, as long as I don't refresh the app, my downloaded chapters keep working as expected, but if I refresh the page they disappear until the server is back on. This isn't a big issue, but it is annoying.

https://github.com/Aidoku/Aidoku/assets/16142485/bdb830ac-7d75-412c-be95-b9ff94a5439e

**Comment by Skittyblock** [comment]
hmm, yeah, it should detect this and disable the chapter fetching.
