### ISSUE TITLE
Add Swedish to Weblet for translation

### ISSUE THREAD

**Issue by Weevild** [Aidoku/Aidoku#337]
Hi, I'd like to volunteer myself for the task of translating the app into Swedish but the language isn't added to the Weblet page as of now. If that could be done I'd be more than happy to take on the task of translation.

**Comment by Skittyblock** [comment]
If you create a weblate account then you should be able to add it yourself, but I went ahead and added it for you. https://hosted.weblate.org/projects/aidoku/strings/sv/
