### ISSUE TITLE
Resized Icons in MigrateSourcesView

### ISSUE THREAD

**Issue by aphronyx** [Aidoku/Aidoku#338]
![image](https://github.com/Aidoku/Aidoku/assets/64679454/9915091c-0d4a-4653-93e3-97945b87b80e)

## Environment

- Aidoku version: 0.6.5 (2)
- Device model: iPhone SE (2nd generation)
- OS version: iOS 16.6

**Comment by aphronyx** [comment]
Covers are overlapping in MigrateSearchMatchView.
![image](https://github.com/Aidoku/Aidoku/assets/64679454/9da41184-3c20-43c9-8020-b896a652d982)

**Comment by aphronyx** [comment]
Covers are not cropped to the same aspect ratio.
![image](https://github.com/Aidoku/Aidoku/assets/64679454/7eada116-7bdb-4ae6-85bc-fbeb4c1517f4)

**Comment by aphronyx** [comment]
Should I create separate issues?

**Comment by Skittyblock** [comment]
Nah, these are SwiftUI issues from the Nuke 12 migration. I'll look into it.
