### ISSUE TITLE
Download with Wi-Fi only toggle option 

### ISSUE THREAD

**Issue by togwrlp** [Aidoku/Aidoku#348]
Thinking of the feature that Tachiyomi also had of being able download only with Wi-Fi as a toggle like the one that is currently on library update
![Only on Wifi option](https://github.com/Aidoku/Aidoku/assets/144398543/e2b94930-a202-4618-a44a-1822938c1a30)

**Comment by Skittyblock** [comment]
should be pretty easy; I'm thinking downloads should probably still be queued, but we could do a reachability check to pause downloading whenever not on wifi
