### ISSUE TITLE
MAL tracker not updating reading status

### ISSUE THREAD

**Issue by Thedarkskin123** [Aidoku/Aidoku#355]
Every time when I’m about to change the status to “finished” it will not refresh and is going to change back to “reading” even though I pressed on finished.

https://github.com/Aidoku/Aidoku/assets/146199251/bc6cb80c-7101-4e87-9c7e-6f1465a7bea4

**Comment by Haulien** [comment]
Also experiencing this. However if you set the status on MAL directly, it gets updated in Aidoku.

**Comment by Thedarkskin123** [comment]
> Also experiencing this. However if you set the status on MAL directly, it gets updated in Aidoku. 

How do you do this ?

**Comment by Haulien** [comment]
> > Also experiencing this. However if you set the status on MAL directly, it gets updated in Aidoku.
> 
> How do you do this ?

on MALs website, when you update the status directly. 

You can search for it manually in safari, or you can get straight to the manga through Aidoku, as shown below. 

Open the tracker menu, press the 3 red dots, and press "View on website"

<img src="https://i.imgur.com/KCNOgAB.jpg" width="400" />

Then on MAL, make sure you are logged in (the login button should be on the top right) find the list features (should be directly below the score), and change reading to whatever you wish. 

<img src="https://i.imgur.com/LUscTDN.jpg" width="400" />

Close MAL, close Aidoku's tracker menu, and when the menu is re-opened your change should show up in Aidoku!

**Comment by Thedarkskin123** [comment]
> wish.
> 
> 
> 
> Close MAL, close Aidoku's tracker menu, and when the menu is re-opened your change should show up in Aidoku!

Ok thank you
