### ISSUE TITLE
Enhance Manga Page Reading Direction

### ISSUE THREAD

**Issue by JamerroneCF** [Aidoku/Aidoku#367]
**Goal:**
I'd like to suggest improving the manga reading experience in this application. Currently, pages are displayed from left to right. I propose adding an option to read pages from right to left, following the traditional manga reading style.

**Why This Is Important:**
Reading right-to-left is common in manga, and this change would make the digital experience more intuitive for users familiar with physical manga.

**Suggested Implementation:**
Add a user-selectable option to choose the reading direction. Default can remain left-to-right, but users can switch to right-to-left if they prefer.

**Comment by Skittyblock** [comment]
this is already implemented, the default is right-to-left, and most sources auto-detect the correct reading direction if you set it to automatic. you can change global reading direction in settings tab or do it per-manga with the Aa button while reading.
