### ISSUE TITLE
MAL Tracker Disconnect/Expire

### ISSUE THREAD

**Issue by Googolplexed0** [Aidoku/Aidoku#374]
Currently, the MAL tracker fails approximately every two months. Manga series with a previously functional MAL tracker will show all null values (excepting Status, which shows its default, Reading). 

Current fix requires me to make a backup, Log Out from MAL on the Trackers tab (which deletes all MAL trackers currently attached to mangas), Log In and repeat the MAL authorization agreement, and then load the backup made in step one since all mangas have been stripped of their trackers (very very slow since my library is very large ~30 minutes).

**Comment by Skittyblock** [comment]
I tried fixing this issue a while back with bb437f6 but it must've not worked...

**Comment by Skittyblock** [comment]
Might have been fixed by cd8b5b525c8d77628e3d29ee94a488abcf935f21
