### ISSUE TITLE
Auto Backup Trigger

### ISSUE THREAD

**Issue by aphronyx** [Aidoku/Aidoku#380]
not sure if this is the duplicate of #88, but i assume that one is to create backups at a time interval.
while this issue suggest providing options to users to auto create backups when

- adding/removing manga to/from library
- catching up to a manga
- library updated

and keep up to the number of backups or the total size of backups

**Comment by Skittyblock** [comment]
Can probably add these requests to that issue as additional requested features, since it hasn't been implemented at all yet.
