### ISSUE TITLE
Sort by Recent Activity

### ISSUE THREAD

**Issue by aphronyx** [Aidoku/Aidoku#381]
last opened & last updated

**Comment by Skittyblock** [comment]
You want an option that combines these?

**Comment by aphronyx** [comment]
yes, sort by the later of two

| | A | B | C | D | E | F | G | H | I | J |
| :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| **Last Opened** | 21 Nov. 2023 | 26 Nov. 2023 | 07 Nov. 2023 | 22 Nov. 2023 | 16 Nov. 2023 | 24 Nov. 2023 | 18 Nov. 2023 | 07 Nov. 2023 | 23 Nov. 2023 | 21 Nov. 2023 |
| **Last Updated** | 20 Nov. 2023 | 09 Nov. 2023 | 01 Nov. 2023 | 22 Nov. 2023 | 21 Nov. 2023 | 08 Nov. 2023 | 23 Nov. 2023 | 28 Nov. 2023 | 21 Nov. 2023 | 09 Nov. 2023 |

➡️ H B F I G D A E J C

**Comment by Skittyblock** [comment]
I feel like this is too niche of an option. Sorting by last opened and then pinning updated manga makes more sense to me, since it should be similar behavior.
