### ISSUE TITLE
Label Manga Added from Other Source in Browse View

### ISSUE THREAD

**Issue by aphronyx** [Aidoku/Aidoku#382]
same manga can exist in different sources, labelling them can prevent users from adding duplicate manga to library.
this would be more convenient when migrating manga to other source.

## More Features

- switch manga between different sources in manga view

**Comment by Skittyblock** [comment]
I'm not sure I entirely know what you're asking for... Do you mean you want manga to be marked while browsing other sources if they've been added to your library from another source already?

**Comment by aphronyx** [comment]
> Do you mean you want manga to be marked while browsing other sources if they've been added to your library from another source already?

yes

**Comment by Skittyblock** [comment]
I don't think this is very realistic since there's no consistent way to correctly match the same manga from different sources, so it could lead to accidental matches or at the very least be something unreliable and not entirely useful...

**Comment by aphronyx** [comment]
> I don't think this is very realistic since there's no consistent way to correctly match the same manga from different sources, so it could lead to accidental matches or at the very least be something unreliable and not entirely useful...

oh sorry, i was thinking a feature users could do it manually, not auto detect by aidoku

**Comment by Skittyblock** [comment]
is there a reason to manually mark manga in other sources as already in your library? I think maybe the ability to merge manga from different sources into one library entry might be something useful, albeit not really a priority as a feature

**Comment by aphronyx** [comment]
> is there a reason to manually mark manga in other sources as already in your library?

i have over 1,000 manga in my library, so it’s difficult for me to remember which manga i’ve already added. plus, same manga can have different title in different sources, making it more difficult to search, especially chinese title, in library
