### ISSUE TITLE
Cover View Shows Nothing

### ISSUE THREAD

**Issue by aphronyx** [Aidoku/Aidoku#388]
Some websites only display manga covers on the search page, but not on the manga/chapter pages, i.e. [MyReadingManga](https://myreadingmanga.info/)(❗NSFW❗). Therefore, I only return the cover url in the [`get_manga_list`](https://github.com/Skittyblock/aidoku-community-sources/blob/6ac77a63245521809566382d391e08dc8c68ea2a/src/rust/multi.myreadingmanga/src/lib.rs#L95), but an empty cover string in the [`get_manga_details`](https://github.com/Skittyblock/aidoku-community-sources/blob/6ac77a63245521809566382d391e08dc8c68ea2a/src/rust/multi.myreadingmanga/src/lib.rs#L181). However, this causes the cover view to show an empty frame when I tap on the cover in the manga view.
Should I fix this in source, or is this a bug?

**Comment by Skittyblock** [comment]
Not a bug, but it's a limitation with aidoku-rs. Whatever you send back in `get_manga_details` will be used as the manga object in the manga page, but aidoku-rs doesn't serialize the whole manga object that aidoku sends, so you can't reuse the old fields. This will work better with the new source api.

**Comment by aphronyx** [comment]
it actually fixed on 0.6.8, so it probably was because of #432
