### ISSUE TITLE
Read all button when you press and hold the cover art.

### ISSUE THREAD

**Issue by ojvaj1** [Aidoku/Aidoku#389]
Not really an important thing to add just a nice to have. But when you press and hold the cover of a series that you could click a read all button.

https://github.com/Aidoku/Aidoku/assets/60130104/549a4796-6448-421c-8d7d-c4078e4c003a

Hope you get what I mean. Love the app so far great job :)

**Comment by apix0n** [comment]
bump; this was added in #474
