### ISSUE TITLE
Issue with Library Update for Large Collections (>400 Entries)

### ISSUE THREAD

**Issue by aurimasniekis** [Aidoku/Aidoku#391]
## Description:
I've encountered a problem with updating manga in libraries that have more than 400 entries. Specifically, some manga that I've read and are continuously updating do not appear at the top of the 'Library' list, despite having recent chapters available.

## Steps to Reproduce:
1 .Open a library with more than 400 manga entries.
2. Observe the 'Library' list (Sort by updated date, so that latest updates on top).
3. Notice that some continuously updating manga do not appear at the top, despite having new chapters.
4. Confirm by visiting the source website, which shows additional chapters not listed in the app.
5. Perform a library refresh, but note that the update does not reflect the new chapters (the loading indicator may also freeze during this process).
6. Open an individual manga and pull down to refresh within the book view. This action successfully updates the manga with new chapters.

## Expected Behavior:
The 'Library' list should accurately reflect the most recent chapters of continuously updating manga. The library refresh feature should update all entries accordingly without requiring individual book view refreshes.

## Actual Behavior:
The 'Library' list does not update for certain manga in large libraries. A full library refresh fails to update these entries, and only a refresh in the individual book view reflects the new chapters.

## Suggestion:
Improving the loading indicator to better reflect the status of the update process would enhance the user experience, especially during long refresh times.

## Environment:
Aidoku version: `0.6.6 (Build: 2)`
iOS version: `17.1.2`
Device: `iPhone 15 Pro Max`

## Additional Information:
This issue has been observed with several books across different sources, indicating that it might not be solely related to a specific source.

**Comment by aurimasniekis** [comment]
In addition to the issue described above, I'd like to suggest an enhancement that could improve the user experience and potentially alleviate part of the problem. It would be beneficial to have the ability to refresh the content from a specific source directly, rather than refreshing the entire library.

## Feature Description:

* **Source-Specific Refresh:** Allow users to select a specific source and initiate a refresh only for manga from that source. This could be particularly helpful in large libraries where a full library refresh is time-consuming and may lead to the issues mentioned earlier.
* **Progress Indicator:** Implement a progress bar or a similar indicator for the refresh process. This would provide visual feedback to the user about the progress of the update, especially useful when dealing with large amounts of data or slower connections.

I believe this feature could not only make the app more efficient for those with extensive libraries but also provide a better overall user experience by giving more control and feedback during the update process.

Looking forward to your thoughts on this suggestion.

**Comment by Skittyblock** [comment]
> the loading indicator may also freeze during this process
this happens if you switch off the library page while it's refreshing

> the update does not reflect the new chapters
did you check your library refresh options in settings? by default, titles that have unread chapters and are marked as completed don't update during library refreshes.

A better indicator for library update progress is planned, once I figure out the best way to do it. You can make a separate issue for the source-specific refresh feature request if you'd like.

**Comment by Skittyblock** [comment]
Closing this due to lack of information. My guess is that either the DDOS mitigation settings are causing library titles to not update during full library refreshes or the app is being closed while halfway through a library refresh, canceling it. A better progress indicator for library refreshes will be coming, but feel free to make a new GitHub issue for it if you would like.
