### ISSUE TITLE
ReadManga issues

### ISSUE THREAD

**Issue by stancuem** [Aidoku/Aidoku#395]
There are some problems with using the ReadManga (RU) source. The source itself is working stably. You can view the manga through the app, and it is also updated. The problem is that it is impossible to read manga from this source, there is an eternal download. Sometimes a message appears (literally translated from Russian) "You are offline or the source is unavailable." Not only I complain about this problem, but several other users.
Thank you very much
![e7748acf-e213-480b-ade8-1ca93d022401](https://github.com/Aidoku/Aidoku/assets/129685009/670609bc-fb01-46e7-9368-2f591f4467ab)

**Comment by Serrkkaa** [comment]
I have such a problem too.

**Comment by Skittyblock** [comment]
Oops, this is the wrong GitHub repo for source issues. Aidoku doesn't have control over any individual source issues.
