### ISSUE TITLE
MyAnimeList Tracker search broken

### ISSUE THREAD

**Issue by twxxle** [Aidoku/Aidoku#397]
When I try to track something with MAL, it displays empty results and sometimes even nothing. It works perfectly with AniList.

![IMG_0657](https://github.com/Aidoku/Aidoku/assets/107503257/6bca7262-7477-4634-b623-25f04e0b9efa)

![IMG_0658](https://github.com/Aidoku/Aidoku/assets/107503257/d043f75a-d2db-48b3-a1b3-361ae0821383)

**Comment by Skittyblock** [comment]
looks like this is still #374
