### ISSUE TITLE
Face/Touch ID for locking library categories

### ISSUE THREAD

**Issue by k3lux** [Aidoku/Aidoku#40]
The app is amazing so far, but I think an unlock with Face/Touch ID would be a good feature to add

**Comment by AzSiAz** [comment]
Maybe not app wide but by collection ?

**Comment by Skittyblock** [comment]
Yeah, I'm thinking that locking specific places such as library collections would be a better idea rather than locking the entire app.

**Comment by Skittyblock** [comment]
The library, specific categories, and history can now all be locked by face/touch id.
