### ISSUE TITLE
Downloaded chapters disappear when offline if you pull to refresh

### ISSUE THREAD

**Issue by mlynni** [Aidoku/Aidoku#409]
I don't know if this is a bug or more of a feature request, but right now if you are offline and accidentally pull to refresh on the manga page, even downloaded chapters disappear, which shouldn't be the case.
![image](https://github.com/Aidoku/Aidoku/assets/17209851/e7e4a9f5-b8ee-4ce8-b747-6d7d0c2d9041)

**Comment by Skittyblock** [comment]
forgot about this, it should check if you're offline #336
