### ISSUE TITLE
Cover with Cloudflare Won't Display in Cover View

### ISSUE THREAD

**Issue by aphronyx** [Aidoku/Aidoku#432]
When website maintainers enable Cloudflare challenges, the cover can only be displayed in manga view, not cover view. I tried printing the cover URL in `get_manga_details`, and it correctly printed the URL.

**Comment by Skittyblock** [comment]
Is there a source I can test with?

**Comment by aphronyx** [comment]
> Is there a source I can test with?

[zh.boylove](https://github.com/aphronyx/aidoku-community-sources/tree/48feb52d40a713c62a52a2056190bcc22ea8bbe7/src/rust/zh.boylove) had this issue at the time, but the maintainers have disabled Cloudflare challenges, so it works correctly now.

**Comment by axiel7** [comment]
I can reproduce it with es.tumangaonline

I'll see if I can fix it
