### ISSUE TITLE
Reading mode

### ISSUE THREAD

**Issue by 1917431753** [Aidoku/Aidoku#434]
Reading mode:webcomic，Repeated flash back.Pulling down multiple pages at once can easily lead to crashes, even when reading normally. The more pages a chapter has, the higher the likelihood of a crash. It is difficult for you to read more than a hundred pages of chapters, and the position of the progress bar that pulls the reading is also very inaccurate

**Comment by Skittyblock** [comment]
#353, #418, etc.
