### ISSUE TITLE
Cloudflare Bypass Issue

### ISSUE THREAD

**Issue by AlokSwaminathan** [Aidoku/Aidoku#440]
After a source (in my case ManhuaUS) needs cloudflare to be bypassed (When I click the safari icon in the top right it goes through cloudflare, after that happens once it works without cloudflare for a while), it just completely stops working

![image](https://github.com/Aidoku/Aidoku/assets/74495591/890bff7e-3b7b-45b4-beaf-aecedff67101)

The source is stuck on that loading page, and when I try to update my library (which has ManhuaUS manhwas), it never finishes updating, and I have to fully close and reopen the app for it to show the updates from other, working sources.

I am willing to try to tackle this issue myself if someone could point me in the right direction or help me figure out where to start.

**Comment by Skittyblock** [comment]
Completing the CloudFlare thing in the web view doesn't have any effect on Aidoku since it's performed in a separate process, but CloudFlare updated their captcha page so Aidoku needs to adjust its bypass method a bit.
