### ISSUE TITLE
Chapter don’t load on sushi-scan

### ISSUE THREAD

**Issue by ryo-sama** [Aidoku/Aidoku#447]
Hi, I have an issue with the sushi scan source, the cloudfare works but I cant read any manga, it says that the chapter can’t load

https://github.com/Aidoku/Aidoku/assets/141324250/2ac0f8b5-b2be-415a-aca5-062a032894e1

**Comment by GAMADA06** [comment]
Same ! The cloudflare bypass works but it cant load the chapters

**Comment by Skittyblock** [comment]
this is an issue with a source, not aidoku.
