### ISSUE TITLE
Can't get back into Aidoku after uninstall

### ISSUE THREAD

**Issue by Hisaxdd** [Aidoku/Aidoku#450]
Uninstalled Aidoku b/c needed to uninstall to fix something and then now when I try to rejoin I get a message popping out with a header saying "Couldn't load app" and "This invitation has been revoked or is invalid. Request a new invitation from the developer" (am currently paying for supporter on discord.

**Comment by Skittyblock** [comment]
Please request help in the #supporter-support channel on Discord and we can manually send you a new invite if the one being sent to you isn't working
