### ISSUE TITLE
Aidoku Lost Everything 

### ISSUE THREAD

**Issue by Kingcole006** [Aidoku/Aidoku#451]
I reinstalled the app and now I’ve lost everything all my mangas, webtoons, manwhas, GONE 😭. I can’t find anything at all can’t even download anything. Here’s images to show what I mean
![IMG_5781](https://github.com/Aidoku/Aidoku/assets/171428637/598f00ce-5740-40c7-9963-e2bd144ecb10)
![IMG_5782](https://github.com/Aidoku/Aidoku/assets/171428637/95bebd02-ac4a-4d19-bc41-b3b3f5eaae91)

**Comment by Skittyblock** [comment]
deleting the app deletes the data, like it says it does. make sure to make a backup in settings and export it somewhere before deleting the app
