### ISSUE TITLE
Duplicate chapters when downloading

### ISSUE THREAD

**Issue by Roroca-1** [Aidoku/Aidoku#460]
downloading 2 different managas(manga A & B)at the same time results in manga B having the same content as manga A until manga A's last page.
eg. Manga A has 17pgs, Manga B has 52pgs, Manga B when finished downloading up to pg17 is just Manga A, and Managa B content from pg18 to pg52

**Comment by Skittyblock** [comment]
This shouldn't be happening. Which source are you using and which manga are you downloading? Does this happen every time?

**Comment by Roroca-1** [comment]
After testing this is a source problem, only happens on a specific source. Every other source works perfectly fine.

**Comment by Skittyblock** [comment]
You can create an issue for the source in whichever repo it's located
