### ISSUE TITLE
Feature Request: Random Manga/Comic Button

### ISSUE THREAD

**Issue by Bugs4life** [Aidoku/Aidoku#462]
I would like to suggest a feature that will allow users to click a button to recieve a random Manga/Comic recommendation, this would provide a quick way to discover new content without having to go through the stress of searching it up manually.

Also, maybe we can have an additional button for seeing Recommendations based on our recent manga/comics?
Would love to see this features on Aidoku.

Thanks!
~Bugs4life

**Comment by Skittyblock** [comment]
Ah, looks like #284 already existed
