### ISSUE TITLE
Failed to Parse HTML

### ISSUE THREAD

**Issue by aphronyx** [Aidoku/Aidoku#468]
https://github.com/Skittyblock/aidoku-community-sources/blob/51649e85a8e2c6a210ef801e6e2a0eaecce166cf/src/rust/zh.boylove/src/lib.rs#L112

This code works in `0.6.8`, but not in `0.6.9`.

## Screenshots

| 0.6.8 | 0.6.9 |
| :-: | :-: |
| ![Simulator Screenshot - iPhone 15 Pro - 2024-08-18 at 17 35 30](https://github.com/user-attachments/assets/d6f45496-f480-420d-a4f1-bd3f5b021d93) | ![Simulator Screenshot - iPhone 15 Pro - 2024-08-18 at 17 37 39](https://github.com/user-attachments/assets/a379a2ae-197b-4496-ba51-c1d25538ac26) |
| | <img width="1136" alt="截圖 2024-08-18 17 40 25" src="https://github.com/user-attachments/assets/12d54294-d590-45f7-91fd-39ca13b7b627"> |
| | <img width="1181" alt="截圖 2024-08-18 17 40 10" src="https://github.com/user-attachments/assets/230fcdc2-264f-4516-80ee-15025db44c0a"> |

**Comment by Skittyblock** [comment]
looks like a SwiftSoup regression in 2.7.3... updated to 2.7.4 and it seems to be resolved.
