### ISSUE TITLE
Refresh button on page

### ISSUE THREAD

**Issue by Roroca-1** [Aidoku/Aidoku#470]
![image](https://github.com/user-attachments/assets/275f6e7c-d40f-45ad-9b4c-c54f42acb831)

Refresh button when a page is displaying properly, the button itself does nothing.

Steps to recreate: Successfully load a page, turn to the next page, turn back to previous page and the refresh button will appear on the previously loaded pages.

So far only happened on 0.6.9

**Comment by Skittyblock** [comment]
I've had this happen to me before but I'm unsure of how to reproduce it. Your instructions don't work for me.

**Comment by purriana** [comment]
This happens to me, too, with the same instructions (going back to previously loaded pages, sometimes takes a few seconds for the “reload” to appear). Only happens while on double page mode, it disappears when on single page. I’m using an iPad pro.

**Comment by Roroca-1** [comment]
> This happens to me, too, with the same instructions (going back to previously loaded pages, sometimes takes a few seconds for the “reload” to appear). Only happens while on double page mode, it disappears when on single page. I’m using an iPad pro.

same in my case, only happens in double page mode
