### ISSUE TITLE
[Feature request] More Raw manga support

### ISSUE THREAD

**Issue by TheFermi0n** [Aidoku/Aidoku#471]
I have recently started learning Japanese, and at my current stage, reading manga in a non-native language doesn’t feel as satisfying.

Even though Aidoku offers some raw manga sources, I would love to see more available. Beginner-friendly websites like [Bilingual Manga](https://bilingualmanga.org/) mostly feature manga recommended by Japanese learning guides.

I know I can always read from those websites, but I would appreciate it if Aidoku could include them in the future.

Thank you very much.

**Comment by Skittyblock** [comment]
aidoku doesn't control any of the sources; they're offered externally. you can request this wherever sources are distributed
