### ISSUE TITLE
Downloading chapters only download one page

### ISSUE THREAD

**Issue by GeneralQuestion** [Aidoku/Aidoku#482]
The downloaded chapters only download 1 page and the app isn’t listing any errors
![IMG_7239](https://github.com/user-attachments/assets/345d0d40-b917-4586-b016-50dcac5ff111)
![IMG_7240](https://github.com/user-attachments/assets/124d5448-5141-4fc5-8a95-5395d61ad1fa)

**Comment by Skittyblock** [comment]
this is something specifically only happening with this one source, but it's probably some sort of thing Aidoku should be working around somehow, so i'll need to investigate further
