### ISSUE TITLE
Feature Request: Improve Double-Page Panel Display

### ISSUE THREAD

**Issue by ccaylak** [Aidoku/Aidoku#483]
Hello Aidoku Team,

I really enjoy using your app, especially on my iPad. I particularly like reading in horizontal mode, as it feels more like reading a real manga rather than something digital.

However, I've encountered some issues when reading in horizontal mode, especially with double-page spreads. I reported this in the support channel, and it was explained that the problem depends on the source and how the pages were scanned.

That being said, I recently tried another manga reading app similar to Aidoku, and the double-page spreads work fine there.

I've attached two screenshots that illustrate the issue. The first one is from Aidoku, and the second one is from the other app. In both cases, I'm using the iPad version with Mangasee as the source, so the sources should be identical.
![Aidoku](https://github.com/user-attachments/assets/2388a445-9d29-4dc5-824c-ef7993342109)
![Suwatta](https://github.com/user-attachments/assets/29a5e4f2-be98-4b09-a710-2ad0cde72826)

**Comment by Skittyblock** [comment]
this is #96
