### ISSUE TITLE
Is there a chance to add the Mac version?

### ISSUE THREAD

**Issue by ryanwuson** [Aidoku/Aidoku#485]
I know that on a Mac, IPA can be installed with SIP-Off, but could you provide a Mac version of the app so that it can be used with SIP-ON? Thank you.

**Comment by Skittyblock** [comment]
i'm pretty sure ipas can be installed on macs without turning off sip... but there's no "mac ipa", macs just use the ipad version of the app. you can also install via testflight

**Comment by ryanwuson** [comment]
> i'm pretty sure ipas can be installed on macs without turning off sip... but there's no "mac ipa", macs just use the ipad version of the app. you can also install via testflight

Yes, you're right, my description is not accurate, unfortunately, the TestFlight slots are full.
