### ISSUE TITLE
Crash on Mac after pressing 'Start Reading'

### ISSUE THREAD

**Issue by ryanwuson** [Aidoku/Aidoku#493]
I installed aidoku version 0.6.10 through TestFlight. All other features are working fine, but the "start reading" function is failing. As soon as I press "start reading," aidoku crashes and an error dialog box appears. The previous version did not have this issue.

My system is macOS 15.1 (24B83). Thank you very much.

![000](https://github.com/user-attachments/assets/31211ca8-7242-4cd9-9769-fb6c6d09340c)
![001](https://github.com/user-attachments/assets/58b37a95-a823-47d9-ac2f-ba897dabaaab)
![002](https://github.com/user-attachments/assets/4706ad38-6169-43a8-88e7-ecff12561e9b)

**Comment by ryanwuson** [comment]
I used App cleaner to completely remove Aidoku and cleaned up all related items in the system. Restarted the Mac, entered safe mode, opened Testflight, installed Aidoku, added Source, read a comic book at will, the app won't crash. Once I quit Aidoku and restart it, the above crash situation will occur.

After that, I tried other methods, and I found that, whether in safe mode or normal mode, as long as it is the first time to download and open Aidoku from Testflight, it can be read normally. Once Aidoku is quit and open again, pressing 'Start Reading' will crash.

Finally, I attach the crash report. My Mac model is M1 Pro. The previous Testflight version would also crash, and I thank you again!

[Translated Report.txt](https://github.com/user-attachments/files/17843645/Translated.Report.txt)

**Comment by Moiz-I** [comment]
Any updates @ryanwuson? I'm having the issue after updating Aidoku. I also updated MacOS to 15.1 - same as you, after which this issue started. Maybe that could be the problem?

**Comment by ryanwuson** [comment]
> Any updates @ryanwuson? I'm having the issue after updating Aidoku. I also updated MacOS to 15.1 - same as you, after which this issue started. Maybe that could be the problem?

It turns out I'm not the only one who discovered the same problem 😆

The developer has not updated yet. My current approach is to use Playcover to install the IPA, but the layout will be slightly different from the one installed from Testflight. If you use Sideloadly to install the IPA, you will also encounter crashes.

We can only wait for the developer to find the real cause and update the app.
