### ISSUE TITLE
Read items don't update on chapter display

### ISSUE THREAD

**Issue by DavidLeBonk** [Aidoku/Aidoku#494]
Not sure if this is just a me issue but after downloading a manga, setting around 3/4 of the chapters to read and then continuing to read the read chapters weren't updating. Like say I read from chapter 50 to 60 the chapter I resume it is still 50 and it's as if the other chapter era weren't even read.

**Comment by Skittyblock** [comment]
is this something consistent? are you sure you don't have incognito mode on?

**Comment by DavidLeBonk** [comment]
Ah my bad, I did t know what incognito mode did. I assumed it would be something to do with randomising headers/simulated web request shit for every download.
