### ISSUE TITLE
iCloud Sync Alternative

### ISSUE THREAD

**Issue by ceyaima** [Aidoku/Aidoku#500]
I'm not a dev so i'm not sure if this is would actually work or not, but since icloud sync doesn't work, couldn't aidoku use anilist to sync between devices? As in, with fixed intervals, aidoku would check anilist for differences in the chapters read. Though this would only work for manga that's already been added to the user's aidoku libary on both devices, I still think it's better than nothing

**Comment by Skittyblock** [comment]
essentially #306
