### ISSUE TITLE
Allowed to switch categories by swiping

### ISSUE THREAD

**Issue by NeKoOuO** [Aidoku/Aidoku#506]
If I wanna change category, I need to tap every time.

The current up and down swipes are for browsing the library, but the left and right swipes have no interaction. I hope the left and right swipes can switch categories.

**Comment by Skittyblock** [comment]
not really planning this since it's not very ios-like. there may be some ui changes in the future with regard to categories, but it's very low priority

**Comment by NeKoOuO** [comment]
I hope there's some new change in the future for the category🙏
I just want to let the category change easier. I don't mind improving in another way.
