### ISSUE TITLE
App crashes when opening certain manhwa

### ISSUE THREAD

**Issue by CinnamonGoat** [Aidoku/Aidoku#507]
When I try to open some manhwa, the app suddenly crashes.
It is always the same ones that crash the app. There are several with this issue, but most if not all using the Asura source.
The crash can happen from either just opening the manhwa to view the chapter list, or to anytime I refresh the page to try and see if there have been any updates.

**Comment by Skittyblock** [comment]
likely fixed by 860330790961fd62cc412567a538e3836c308c58
