### ISSUE TITLE
Lock history when app exits foreground

### ISSUE THREAD

**Issue by Skittyblock** [Aidoku/Aidoku#51]
The history tab currently locks only if it's manually re-locked via button press or if the app fully closes. It should lock again once the app goes into the background even without being fully closed.

**Comment by bdashore3** [comment]
This can be accomplished by adding calls into SceneDelegate's `willResignActive` and `didBecomeActive` methods or through the notification counterpart `willResignActiveNotification` and `didBecomeActiveNotification`
