### ISSUE TITLE
Automatic Download of User-Defined Number of Upcoming Chapters

### ISSUE THREAD

**Issue by manilka12** [Aidoku/Aidoku#515]
automatically downloading a user-defined number of chapters ahead of the current reading position.

Feature Details:
	•	Automatic Pre-Download: As a user reads a chapter, the app would automatically download the next ‘X’ chapters in the background, where ‘X’ is a number set by the user.
	•	User-Defined Settings: Users can specify the number of chapters to be pre-downloaded in the app’s settings.
	•	Storage Management: To prevent excessive storage use, the app could offer options to:
	•	Limit the total number of pre-downloaded chapters.
	•	Automatically delete previously read chapters after a certain period or when storage limits are reached.

**Comment by Jamerrone** [comment]
Love this idea! As I pretty much do the same manually.

**Comment by Skittyblock** [comment]
fits in with #152
