### ISSUE TITLE
Rewrite reader system

### ISSUE THREAD

**Issue by Skittyblock** [Aidoku/Aidoku#59]
The reader mode system code has gotten very messy, and there are a number of issues with the vertical scroll reader in particular. The whole thing desperately needs a rewrite (my plan is to do this after I finish tracker support for 0.5).

**Comment by Skittyblock** [comment]
While I would like to modularize more of the Aidoku code eventually, I'm not sure if the reader system needs to be done that way quite yet. I'll see though.

**Comment by bdashore3** [comment]
The first thing to do is to unify common code and functions between both readers since there is a lot of duplication between both of them
