### ISSUE TITLE
Only 500 chapters are shown

### ISSUE THREAD

**Issue by NoaHimesaka1873** [Aidoku/Aidoku#83]
![D887206C-FCEA-465D-8AFE-29CC58CFDBE2](https://user-images.githubusercontent.com/39993457/177082820-55dcfbc6-41ec-4de0-91ef-c14cae960531.png)
If there's more than 500 chapter for particular manga, only 500 are shown.

**Comment by Skittyblock** [comment]
Issue with the specific source and not the Aidoku app, but it will be fixed with the relevant PR.
