### ISSUE TITLE
Lag when swiping chapters and with slider

### ISSUE THREAD

**Issue by suirobert** [Aidoku/Aidoku#98]
Lags when swiping pages fast. Also the slider and page number don’t update as I swap (if I swap to page 4, the page number and slider takes up to three seconds to update) so it lags if I try to swipe pages really fast to the point I can’t do a thing

**Comment by Dabbing-Guy** [comment]
I have experienced this problem too. It only happens when reading downloaded things. It works perfectly fine when reading things that are not downloaded.

**Comment by tolenet123** [comment]
me too!
